# Generated by Django 4.0.2 on 2022-02-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('image', models.URLField(null=True)),
                ('rate', models.FloatField(null=True)),
            ],
        ),
    ]
