# Generated by Django 4.0.2 on 2022-02-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0003_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Platform',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='Platform',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
