# Generated by Django 4.0.2 on 2022-02-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0005_rename_platform_movie_platform_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='movie',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
