# Generated by Django 4.0.2 on 2022-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0006_alter_movie_options_movie_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('image', models.URLField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-published']},
        ),
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ['-published']},
        ),
        migrations.AddField(
            model_name='serial',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
