# Generated by Django 4.0.2 on 2022-02-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0007_banner_alter_movie_options_alter_serial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='creator',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='date_production',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='describe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='creator',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='date_production',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='describe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='stars',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
