# Generated by Django 4.0.2 on 2022-02-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0008_movie_creator_movie_date_production_movie_describe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['published']},
        ),
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ['published']},
        ),
    ]
