# Generated by Django 4.0.2 on 2022-02-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0009_alter_movie_options_alter_serial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
