# Generated by Django 4.0.2 on 2022-02-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0010_alter_movie_rate_alter_serial_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-published']},
        ),
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ['-published']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
