# Generated by Django 4.0.2 on 2022-02-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0011_alter_movie_options_alter_serial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
