# Generated by Django 4.0.2 on 2022-02-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0012_movie_video_serial_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='choice',
            field=models.CharField(choices=[('Movies', 'Movies'), ('series', 'series')], max_length=50, null=True),
        ),
    ]
