# Generated by Django 4.0.2 on 2022-02-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0013_movie_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='choice',
            field=models.CharField(choices=[('Movies', 'الفيلم'), ('Series', 'المسلسل')], max_length=50, null=True),
        ),
    ]
