# Generated by Django 4.0.2 on 2022-02-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0014_alter_movie_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='choice',
            field=models.CharField(choices=[('الفيلم', 'الفيلم'), ('المسلسل', 'المسلسل')], max_length=50, null=True),
        ),
    ]
