# Generated by Django 4.0.2 on 2022-02-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0015_alter_movie_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='choice',
            field=models.CharField(choices=[('الفيلم', 'الفيلم'), ('المسلسل', 'المسلسل')], max_length=50, null=True),
        ),
    ]
