# Generated by Django 4.0.2 on 2022-02-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0017_rename_serial_shows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='choice',
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(default='الفيلم', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='type',
            field=models.CharField(default='المسلسل', max_length=50, null=True),
        ),
    ]
