# Generated by Django 4.0.2 on 2022-02-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0018_remove_movie_choice_remove_shows_choice_movie_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='durations',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='durations',
            field=models.IntegerField(null=True),
        ),
    ]
