# Generated by Django 4.0.2 on 2022-02-18 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0020_rename_shows_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscar.episode'),
        ),
    ]
