# Generated by Django 4.0.2 on 2022-02-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0021_show_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
