# Generated by Django 4.0.2 on 2022-02-20 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0022_episode_name_episode_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='episode',
        ),
    ]
