# Generated by Django 4.0.2 on 2022-02-20 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0023_remove_show_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscar.show'),
        ),
    ]
