# Generated by Django 4.0.2 on 2022-02-20 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0024_alter_episode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscar.episode'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
