# Generated by Django 4.0.2 on 2022-02-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0025_show_episode_alter_episode_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='episode',
        ),
    ]
