# Generated by Django 4.0.2 on 2022-02-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0026_remove_show_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
