# Generated by Django 4.0.2 on 2022-02-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0027_alter_episode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
