# Generated by Django 4.0.2 on 2022-02-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0034_favourite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
