# Generated by Django 4.0.2 on 2022-02-25 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0035_favourite_image_favourite_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='video',
        ),
        migrations.AlterField(
            model_name='favourite',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oscar.show'),
        ),
    ]
