# Generated by Django 4.0.2 on 2022-03-01 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0038_movie_category_show_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.RemoveField(
            model_name='show',
            name='type',
        ),
    ]
