# Generated by Django 4.0.2 on 2022-03-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0039_remove_movie_type_remove_show_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
