# Generated by Django 4.0.2 on 2022-03-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0040_alter_banner_image_alter_movie_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
