# Generated by Django 4.2.20 on 2025-03-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0043_alter_movie_image_alter_show_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imageUrl',
            field=models.URLField(null=True, verbose_name='imageurl'),
        ),
        migrations.AddField(
            model_name='show',
            name='imageUrl',
            field=models.URLField(null=True, verbose_name='imageurl'),
        ),
    ]
