# Generated by Django 4.2.20 on 2025-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0044_movie_imageurl_show_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='iframe',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='iframe',
            field=models.URLField(null=True),
        ),
    ]
