# Generated by Django 4.2.20 on 2025-03-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0045_episode_iframe_movie_iframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='iframe',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AlterField(
            model_name='episode',
            name='iframe',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='creator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_production',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='durations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Movies'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imageUrl',
            field=models.URLField(blank=True, null=True, verbose_name='imageurl'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='creator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='date_production',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='durations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Series'),
        ),
        migrations.AlterField(
            model_name='show',
            name='imageUrl',
            field=models.URLField(blank=True, null=True, verbose_name='imageurl'),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='rate',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='stars',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
