# Generated by Django 4.2.20 on 2025-03-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0046_remove_movie_iframe_remove_movie_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='iframe',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
