# Generated by Django 4.2.20 on 2025-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0047_movie_iframe_movie_video_alter_episode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='iframe',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
